services:

  db:
    image: postgres:16
    container_name: quizapp_db
    environment:
      # POSTGRES_USER: postgres
      # POSTGRES_PASSWORD: Db@123
      # POSTGRES_DB: quiz_db
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: .  
    container_name: quizapp_web
    # command: python manage.py runserver 0.0.0.0:8000
    command: gunicorn --bind 0.0.0.0:8000 config.wsgi:application
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db

    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}

volumes:
  postgres_data:  


# services:
#   web:
#     build: .
#     container_name: quizapp_web
#     command: python manage.py runserver 0.0.0.0:8000
#     volumes:
#       - .:/app
#     ports:
#       - "8000:8000"
#     depends_on:
#       - db

#   db:
#     image: postgres:16
#     container_name: quizapp_db
#     environment:
#       POSTGRES_DB: quizapp
#       POSTGRES_USER: postgres
#       POSTGRES_PASSWORD: postgres
#     volumes:
#       - postgres_data:/var/lib/postgresql/data
#     ports:
#       - "5432:5432"

# volumes:
#   postgres_data: