# Generated by Django 6.0.7 on 2026-08-06 01:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quize', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cretegory',
            new_name='Category',
        ),
        migrations.RenameField(
            model_name='quiz',
            old_name='category',
            new_name='Category',
        ),
    ]
